version: '3.7'

services:
  rbac-module:
    container_name: rbac-module
    command: sh -lc "npm ci && npm test"
    build:
      context: ./docker
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
